FROM rust:1.88.0-bookworm AS builder

RUN rustup target add wasm32-unknown-unknown

WORKDIR /app
COPY contracts/ .

RUN cargo build --target wasm32-unknown-unknown --release

FROM rust:1.88.0-bookworm AS dev

RUN rustup target add wasm32-unknown-unknown

RUN cargo install cargo-watch --version ^8

WORKDIR /app
COPY contracts/ .

CMD ["cargo", "watch", "-x", "test", "-x", "build"]
